package View;
import Controller.Create_DB;

import javax.swing.*;
import java.awt.event.ActionEvent;
import javax.swing.table.DefaultTableModel;

public class AppointmentView extends javax.swing.JPanel {

    /**
     * Creates new form AppointmentView
     */
    public AppointmentView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        //added by CD
        dconn = new Create_DB();
        model = new DefaultTableModel();
        


        //netbeans info
        pageLabel = new javax.swing.JLabel();
        healthCareNumberBotInput = new javax.swing.JTextField();
        pInfoLabel = new javax.swing.JLabel();
        docIDLabel = new javax.swing.JLabel();
        pNameLabel = new javax.swing.JLabel();
        HCNumLabel = new javax.swing.JLabel();
        pNameInput = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        confirmationIdBotInput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        backButton = new javax.swing.JButton();
        yearLabel = new javax.swing.JLabel();
        yearDropInput = new javax.swing.JComboBox<>();
        step2LAbel = new javax.swing.JLabel();
        monthDropInput = new javax.swing.JComboBox<>();
        monthLabel = new javax.swing.JLabel();
        dayLabelInput = new javax.swing.JLabel();
        dayDropInput = new javax.swing.JComboBox<>();
        timeLabel = new javax.swing.JLabel();
        timeInput = new javax.swing.JComboBox<>();
        adminSsnInput = new javax.swing.JTextField();
        adminSsnLabel = new javax.swing.JLabel();
        drSSNInput = new javax.swing.JTextField();
        drSSNLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        hospitalNameLabel = new javax.swing.JLabel();
        hospitalNameInput = new javax.swing.JTextField();
        wardLabel = new javax.swing.JLabel();
        wardInput = new javax.swing.JTextField();
        roomLabel = new javax.swing.JLabel();
        roomInput = new javax.swing.JTextField();
        reasonSearchLabel = new javax.swing.JLabel();
        reasonSearchInput = new javax.swing.JTextField();
        personnelInput = new javax.swing.JButton();
        createApptButton = new javax.swing.JButton();
        deleteApptButton = new javax.swing.JButton();
        updateApptButton = new javax.swing.JButton();
        pageLabel1 = new javax.swing.JLabel();
        reasonVisitInput = new javax.swing.JTextField();
        reasonVisitLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        confirmationIdTopInput = new javax.swing.JTextField();
        confirmationIdLabel = new javax.swing.JLabel();
        healthCareNumberTopInput = new javax.swing.JTextField();
        confirmationIdLabel1 = new javax.swing.JLabel();
        viewPatientButton = new javax.swing.JButton();

        pageLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pageLabel.setText("Add/Update/Delete Appointments");

        pInfoLabel.setText("Patient Info");

        docIDLabel.setText("Appointment Confirmation ID");

        pNameLabel.setText("Patient Name");
        reasonSearchLabel.setText("Reason for Search");

        HCNumLabel.setText("HC #");

        confirmationIdLabel1.setText("HC Number");

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "ConfirmationID", "Appt_Date", "Pname", "HealthCareNum", "Reason"
                }
        ));
        jTable.setModel(model);
        


        jScrollPane1.setViewportView(jTable);

        yearLabel.setText("Year");

        yearDropInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"", "2023", "2024", "2025"}));

        step2LAbel.setText("Specify Appointment");

        monthDropInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "","January", "February", "March"
        , "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        monthLabel.setText("Month");

        dayLabelInput.setText("Day");

        dayDropInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31" }));

        timeLabel.setText("Time");

        timeInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "","8:00", "9:00", "10:00", "11:00", "12:00", "1:00", "2:00", "3:00", "4:00", "5:00", "6:00", "7:00" }));

        adminSsnLabel.setText("AdminSSN");

        drSSNLabel.setText("Doctor SSN");

        hospitalNameLabel.setText("Hospital Name");

        wardLabel.setText("Ward");

        roomLabel.setText("Room");

        confirmationIdLabel.setText("Appointment Confirmation ID");

        reasonVisitLabel.setText("Reason for Visit");

        reasonVisitLabel.setText("Reason for Visit");

        jLabel2.setText("10001 - 01 - General Room");

        jLabel3.setText("10002 - 02 - Emergency");

        jLabel4.setText("10003 - 03 - Surgery");

        jLabel5.setText("10004 - 04 - Operation");

        jLabel6.setText("Rm No - Ward - Room Type");

        createApptButton.setText("Create");
        createApptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createApptButtonActionPerformed(evt);
            }
        });

        deleteApptButton.setText("Delete");
        deleteApptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteApptButtonActionPerformed(evt);
            }
        });

        updateApptButton.setText("Update");
        updateApptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateApptButtonActionPerformed(evt);
            }
        });
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        personnelInput.setText("View Personnel");
        personnelInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personnelInputActionPerformed(evt);
            }
        });
        viewPatientButton.setText("View Patients");
        viewPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPatientButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(80, 80, 80)
                                                                .addComponent(healthCareNumberTopInput, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addContainerGap(68, Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(10, 10, 10)
                                                                                .addComponent(step2LAbel))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(monthDropInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(22, 22, 22)
                                                                                                .addComponent(monthLabel)))
                                                                                .addGap(18, 18, 18)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(24, 24, 24)
                                                                                                .addComponent(dayLabelInput))
                                                                                        .addComponent(dayDropInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(yearDropInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(42, 42, 42)
                                                                                                .addComponent(yearLabel)))
                                                                                .addGap(42, 42, 42)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(timeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(timeLabel))))
                                                                .addGap(59, 59, 59)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(reasonVisitInput, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(createApptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(56, 56, 56)
                                                                .addComponent(updateApptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(49, 49, 49)
                                                                .addComponent(deleteApptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(reasonVisitLabel)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(hospitalNameLabel)
                                                                        .addComponent(hospitalNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(47, 47, 47)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(wardInput, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(wardLabel))))
                                                .addGap(58, 58, 58))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(80, 80, 80)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(adminSsnInput, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(adminSsnLabel)
                                                                        .addComponent(roomInput, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(roomLabel)
                                                                        .addComponent(confirmationIdTopInput, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(confirmationIdLabel)
                                                                        .addComponent(confirmationIdLabel1))
                                                                .addGap(35, 35, 35)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(drSSNInput, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(drSSNLabel)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                        .addComponent(jLabel2)
                                                                                                        .addComponent(jLabel3)
                                                                                                        .addComponent(jLabel4)
                                                                                                        .addComponent(jLabel5))
                                                                                                .addGap(14, 14, 14))
                                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                                                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(108, 108, 108)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(pNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(pNameLabel))
                                                                                .addGap(35, 35, 35)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(HCNumLabel)
                                                                                        .addComponent(healthCareNumberBotInput, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGap(49, 49, 49)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(docIDLabel)
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(confirmationIdBotInput, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(50, 50, 50)
                                                                                                .addComponent(searchButton))
                                                                                        .addComponent(reasonSearchLabel)
                                                                                        .addComponent(reasonSearchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                        .addComponent(pInfoLabel)
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                .addComponent(pageLabel1)
                                                                                .addGap(224, 224, 224))))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(68, 68, 68)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                .addComponent(backButton)
                                                                                .addGap(89, 89, 89))
                                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addGap(375, 375, 375)
                                .addComponent(pageLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(viewPatientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(personnelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(71, 71, 71)
                                                .addComponent(adminSsnLabel)
                                                .addGap(6, 6, 6)
                                                .addComponent(adminSsnInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(pageLabel)
                                                        .addComponent(personnelInput)
                                                        .addComponent(viewPatientButton))
                                                .addGap(28, 28, 28)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(drSSNLabel)
                                                                .addGap(6, 6, 6)
                                                                .addComponent(drSSNInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(wardLabel)
                                                                        .addComponent(hospitalNameLabel))
                                                                .addGap(6, 6, 6)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(wardInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(hospitalNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(roomLabel)
                                                        .addComponent(reasonVisitLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(roomInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel1))
                                                                .addGap(28, 28, 28)
                                                                .addComponent(confirmationIdLabel)
                                                                .addGap(6, 6, 6)
                                                                .addComponent(confirmationIdTopInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(reasonVisitInput, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(13, 13, 13)
                                                .addComponent(jLabel6)
                                                .addGap(2, 2, 2)
                                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel4)
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel5)))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(updateApptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(deleteApptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(createApptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(confirmationIdLabel1)
                                                .addGap(6, 6, 6)
                                                .addComponent(healthCareNumberTopInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(step2LAbel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(monthLabel)
                                                                                .addGap(4, 4, 4)
                                                                                .addComponent(monthDropInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(dayLabelInput)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(dayDropInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(yearLabel)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(yearDropInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(timeLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(timeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(39, 39, 39)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pageLabel1)
                                .addGap(10, 10, 10)
                                .addComponent(pInfoLabel)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(pNameLabel)
                                        .addComponent(HCNumLabel)
                                        .addComponent(docIDLabel))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(pNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(healthCareNumberBotInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(confirmationIdBotInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(searchButton))
                                .addGap(18, 18, 18)
                                .addComponent(reasonSearchLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reasonSearchInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addComponent(backButton)
                                .addGap(24, 24, 24))
        );
    }// </editor-fold>

    private void viewPatientButtonActionPerformed(ActionEvent evt) {
        MainView mainView = (MainView) SwingUtilities.getWindowAncestor(this);
        mainView.setViewPatientView(new ViewPatientView());
        mainView.setCard(13);
    }

    private void personnelInputActionPerformed(ActionEvent evt) {
        MainView mainView = (MainView) SwingUtilities.getWindowAncestor(this);
        mainView.setPersonnelView(new PersonnelView());
        mainView.setCard(12);
    }

    private void backButtonActionPerformed(ActionEvent evt) {
        MainView mainView = (MainView) SwingUtilities.getWindowAncestor(this);
        mainView.setLoginView(new LoginView());
        mainView.setCard(0);
    }

    private void updateApptButtonActionPerformed(ActionEvent evt) {


       if(!(confirmationIdTopInput.getText().equals(""))){


       String monthToDigit = "01";

       if(monthDropInput.getSelectedItem() == "Janurary"){
               monthToDigit = "01";
       } else if (monthDropInput.getSelectedItem() == "February"){
               monthToDigit = "02";
       }else if (monthDropInput.getSelectedItem() == "March"){
               monthToDigit = "03";
       }else if (monthDropInput.getSelectedItem() == "April"){
               monthToDigit = "04";
       }else if (monthDropInput.getSelectedItem() == "May"){
               monthToDigit = "05";
       }else if (monthDropInput.getSelectedItem() == "June"){
               monthToDigit = "06";
       }else if (monthDropInput.getSelectedItem() == "July"){
               monthToDigit = "07";
       }else if (monthDropInput.getSelectedItem() == "August"){
               monthToDigit = "08";
       }else if (monthDropInput.getSelectedItem() == "September"){
               monthToDigit = "09";
       }
       else if (monthDropInput.getSelectedItem() == "October"){
               monthToDigit = "10";
       }
       else if (monthDropInput.getSelectedItem() == "November"){
               monthToDigit = "11";
       }
       else if (monthDropInput.getSelectedItem() == "December"){
               monthToDigit = "12";
       }else if (monthDropInput.getSelectedItem() == ""){
               monthToDigit = "";
       }

       String app_time = yearDropInput.getSelectedItem() + "-" + monthToDigit + "-" + dayDropInput.getSelectedItem() + " "+ timeInput.getSelectedItem() + ":00";

       if(yearDropInput.getSelectedItem().equals("") && yearDropInput.getSelectedItem().equals("") && yearDropInput.getSelectedItem().equals("")){
               app_time = "";
       }

       dconn.UpdateAppointment(hospitalNameInput.getText(),wardInput.getText(),roomInput.getText(),app_time,reasonVisitInput.getText(),confirmationIdTopInput.getText());

       String appDate = yearDropInput.getSelectedItem() + "-" + monthDropInput.getSelectedItem() + "-" + dayDropInput.getSelectedItem() + " " + timeInput.getSelectedItem() + ":00" ;
       data = dconn.searchAppointment(pNameInput.getText(),healthCareNumberBotInput.getText(),appDate,confirmationIdBotInput.getText(),pNameInput.getText());
       model.setDataVector(data, colNames);



       }else {
               JOptionPane.showMessageDialog(null, "Must have Document Number.");
       }
       // TODO add your handling code here:
    }

    private void deleteApptButtonActionPerformed(ActionEvent evt) {

       dconn.DeleteAppointment(confirmationIdTopInput.getText());

    }

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {


       String appDate = yearDropInput.getSelectedItem() + "-" + monthDropInput.getSelectedItem() + "-" + dayDropInput.getSelectedItem() + " " + timeInput.getSelectedItem() + ":00" ;

       data = dconn.searchAppointment(pNameInput.getText(),healthCareNumberBotInput.getText(),appDate,confirmationIdBotInput.getText(),reasonSearchInput.getText());
       model.setDataVector(data, colNames);

        // TODO add your handling code here:
    }
    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {
        MainView mainView = (MainView) SwingUtilities.getWindowAncestor(this);
        mainView.setLoginView(new LoginView());
        mainView.setCard(0);
    }

    private void createApptButtonActionPerformed(java.awt.event.ActionEvent evt) {



       String monthToDigit = "01";

       if(monthDropInput.getSelectedItem() == "Janurary"){
               monthToDigit = "01";
       } else if (monthDropInput.getSelectedItem() == "February"){
               monthToDigit = "02";
       }else if (monthDropInput.getSelectedItem() == "March"){
               monthToDigit = "03";
       }else if (monthDropInput.getSelectedItem() == "April"){
               monthToDigit = "04";
       }else if (monthDropInput.getSelectedItem() == "May"){
               monthToDigit = "05";
       }else if (monthDropInput.getSelectedItem() == "June"){
               monthToDigit = "06";
       }else if (monthDropInput.getSelectedItem() == "July"){
               monthToDigit = "07";
       }else if (monthDropInput.getSelectedItem() == "August"){
               monthToDigit = "08";
       }else if (monthDropInput.getSelectedItem() == "September"){
               monthToDigit = "09";
       }
       else if (monthDropInput.getSelectedItem() == "October"){
               monthToDigit = "10";
       }
       else if (monthDropInput.getSelectedItem() == "November"){
               monthToDigit = "11";
       }
       else if (monthDropInput.getSelectedItem() == "December"){
               monthToDigit = "12";
       }else if (monthDropInput.getSelectedItem() == ""){
               monthToDigit = "";
       }

       String app_time = yearDropInput.getSelectedItem() + "-" + monthToDigit + "-" + dayDropInput.getSelectedItem() + " "+ timeInput.getSelectedItem() + ":00";






       if (adminSsnInput.getText().equals("") || drSSNInput.getText().equals("") || hospitalNameInput.getText().equals("") || wardInput.getText().equals("") || roomInput.getText().equals("")) {
               JOptionPane.showMessageDialog(null, "Missing adminSSN, doctorSSN, Hospital ID, Ward, and/or Room no.");
           } else {
               dconn.InsertAppointment(healthCareNumberTopInput.getText(), drSSNInput.getText(), adminSsnInput.getText(), hospitalNameInput.getText(), wardInput.getText(), roomInput.getText(),app_time,reasonVisitInput.getText());
           }


        // TODO add your handling code here:


    }


    // Variables declaration - do not modify
    private javax.swing.JLabel HCNumLabel;
    private javax.swing.JTextField adminSsnInput;
    private javax.swing.JLabel adminSsnLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField confirmationIdBotInput;
    private javax.swing.JLabel confirmationIdLabel;
    private javax.swing.JLabel confirmationIdLabel1;
    private javax.swing.JTextField confirmationIdTopInput;
    private javax.swing.JButton createApptButton;
    private javax.swing.JComboBox<String> dayDropInput;
    private javax.swing.JLabel dayLabelInput;
    private javax.swing.JButton deleteApptButton;
    private javax.swing.JLabel docIDLabel;
    private javax.swing.JTextField drSSNInput;
    private javax.swing.JLabel drSSNLabel;
    private javax.swing.JTextField healthCareNumberBotInput;
    private javax.swing.JTextField healthCareNumberTopInput;
    private javax.swing.JTextField hospitalNameInput;
    private javax.swing.JLabel hospitalNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable;
    private javax.swing.JComboBox<String> monthDropInput;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JLabel pInfoLabel;
    private javax.swing.JTextField pNameInput;
    private javax.swing.JLabel pNameLabel;
    private javax.swing.JLabel pageLabel;
    private javax.swing.JLabel pageLabel1;
    private javax.swing.JButton personnelInput;
    private javax.swing.JTextField reasonSearchInput;
    private javax.swing.JLabel reasonSearchLabel;
    private javax.swing.JTextField reasonVisitInput;
    private javax.swing.JLabel reasonVisitLabel;
    private javax.swing.JTextField roomInput;
    private javax.swing.JLabel roomLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel step2LAbel;
    private javax.swing.JComboBox<String> timeInput;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JButton updateApptButton;
    private javax.swing.JButton viewPatientButton;
    private javax.swing.JTextField wardInput;
    private javax.swing.JLabel wardLabel;
    private javax.swing.JComboBox<String> yearDropInput;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration


    //Added by CD
    private Create_DB dconn;
    private Object[][] data;
    private DefaultTableModel model;
    private String[] colNames = {"ConfirmationID","Hospital", "Ward","RoomNo","Appt_Date", "Pname", "HealthCareNum", "Reason"};

}

