package View;

import Controller.Create_DB;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;

public class LabTechView extends javax.swing.JPanel {

    /**
     * Creates new form LabTechView
     */
    public LabTechView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        // Added by SR
        dconn = new Create_DB();
        model = new DefaultTableModel();

        pageLabel2 = new javax.swing.JLabel();
        HcnInput = new javax.swing.JTextField();
        HCNumLabel = new javax.swing.JLabel();
        resultsLabel = new javax.swing.JLabel();
        docIDInput = new javax.swing.JTextField();
        docIDLabel = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        resultsTable = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        searchResultsLabel = new javax.swing.JLabel();
        labReqLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pageLabel1 = new javax.swing.JLabel();
        updateLabButton = new javax.swing.JButton();
        successLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        pageLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pageLabel2.setText("Update Lab Results");


        HCNumLabel.setText("HC #");

        resultsLabel.setText("Results");

        docIDLabel.setText("DocumentID");

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        model.setDataVector(new Object[][]{null,null,null,null,null}, colNames);

        jTable.setModel(model);
        resultsTable.setViewportView(jTable);

        searchResultsLabel.setText("Search Results");

        labReqLabel.setText("Search for Lab Requisition");

        pageLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pageLabel1.setText("Lab Tech Page");

        updateLabButton.setText("Update");
        updateLabButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateLabButtonActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(95, 95, 95)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(HCNumLabel)
                                                                        .addComponent(HcnInput, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(labReqLabel))
                                                                .addGap(53, 53, 53)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(docIDLabel)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(docIDInput, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(114, 114, 114)
                                                                                .addComponent(searchButton))))
                                                        .addComponent(resultsTable, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(searchResultsLabel)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(421, 421, 421)
                                                .addComponent(pageLabel2))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(97, 97, 97)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(exitButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(updateLabButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(successLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addComponent(resultsLabel)
                                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(0, 31, Short.MAX_VALUE)))))
                                .addContainerGap(73, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(432, 432, 432)
                                        .addComponent(pageLabel1)
                                        .addContainerGap(455, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(73, Short.MAX_VALUE)
                                .addComponent(labReqLabel)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(HCNumLabel)
                                                .addGap(6, 6, 6)
                                                .addComponent(HcnInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(docIDLabel)
                                                .addGap(6, 6, 6)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(docIDInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(searchButton))))
                                .addGap(45, 45, 45)
                                .addComponent(searchResultsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resultsTable, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pageLabel2)
                                .addGap(58, 58, 58)
                                .addComponent(resultsLabel)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(exitButton)
                                                .addGap(20, 20, 20))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(updateLabButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(successLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(48, 48, 48))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(pageLabel1)
                                        .addContainerGap(902, Short.MAX_VALUE)))
        );
    }// </editor-fold>

    // Variables declaration - do not modify
    private javax.swing.JLabel HCNumLabel;
    private javax.swing.JTextField HcnInput;
    private javax.swing.JTextField docIDInput;
    private javax.swing.JLabel docIDLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labReqLabel;
    private javax.swing.JLabel pageLabel1;
    private javax.swing.JLabel pageLabel2;
    private javax.swing.JLabel resultsLabel;
    private javax.swing.JScrollPane resultsTable;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel searchResultsLabel;
    private javax.swing.JLabel successLabel;
    private javax.swing.JButton updateLabButton;


    // ----------------- Added by SR -----------------

    private DefaultTableModel model;
    private Create_DB dconn;
    private Object[][] data;
    private String[] colNames = new String[]{"Document ID", "Health Care Number","Patient Name", "Test Type", "Notes", "Result"};
    private void updateLabButtonActionPerformed(ActionEvent evt) {

        dconn.UpdateLabTest(Integer.parseInt(HcnInput.getText()), Integer.parseInt(docIDInput.getText()), jTextArea1.getText());
        data = dconn.searchLabTest(docIDInput.getText(),HcnInput.getText());
        model.setDataVector(data, colNames);
        successLabel.setText("Test results updated successfully");
    }

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {
        MainView mainView = (MainView) SwingUtilities.getWindowAncestor(this);
        mainView.setLoginView(new LoginView());
        mainView.setCard(0);
    }

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {
        data = dconn.searchLabTest(docIDInput.getText(),HcnInput.getText());
        model.setDataVector(data, colNames);

    }
}
